// Trevis J Fields
// Created OCT 11 08:18
// A SIMPLE JAVA APPLICTION CREATED USING XCODE IDE AND TERMINAL ON A MAC


public class HelloWorld
{
		 public static void main(String[] args)
		 {
					System.out.println("Hello World!");
		 }
}

/*
 --> NOTES:
 - CREATED A FILE USING XCODE AND AN EMPTY BUILD FILE TO CREATE A JAVA PROGRAM.
 - SAVED FILE AS A .JAVA APPLICATION
 - OPENED TERMINAL AND CHANGED DIRECTORY TO FILE LOCATION
 - USED JAVAC TO CREATE THE FILES TO BE RUN IN THE TERMINAL
 - USED JAVA TO DISPLAY THE FILE BACK IN THE TERMINAL TO MAKE SURE THAT THE FILE WAS THERE AND CORRECT
 */
